name: volshebnik
favicon: null
layout_spectrum: 0.031644892413169146
typography_spectrum: 0.5661743637174368
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9115344509482384
  lightness: 0.03337462851777673
  saturation: 0.9294123877771199
  rhythmicContrast: 0.04759423737414181
purpose: []
